server:
  port: 7070
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postolegal
    username: postolegal
    password: 12345
    # Number of ms to wait before throwing an exception if no connection is available.
    max-wait: 1000
    # Maximum number of active connections that can be allocated from this pool at the same time.
    max-active: 4
    # Validate the connection before borrowing it from the pool.
    test-on-borrow: true
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
