server:
  port: 7070
endpoints:
  shutdown:
    enabled: true
    path: /sair
security:
  user:
    name: admin
    password: 12345
management:
  security:
    role: SUPERUSER
spring:
  jpa:
    show-sql: true
    database: HSQL
    url: jdbc:hsqldb:mem:testdb
    hibernate:
      ddl-auto: create